test k8s 5

diff --git a/.github/workflows/deploy-to-eks.yml b/.github/workflows/deploy-to-eks.yml
--- a/.github/workflows/deploy-to-eks.yml
+++ b/.github/workflows/deploy-to-eks.yml
@@ -93,12 +93,16 @@ jobs:
         run: |
           curl -Lo aws-iam-authenticator https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/latest/download/aws-iam-authenticator_$(uname -s)_amd64
           chmod +x aws-iam-authenticator
-          sudo mv aws-iam-authenticator /usr/bin/
-      
-      - name: Check if aws-iam-authenticator is installed
-        run: |
-          which aws-iam-authenticator || echo "aws-iam-authenticator not found"
+          pwd
+          ls -la
+          ls -al /usr/local/bin
+          echo $PATH
           aws-iam-authenticator help
+          
+      # - name: Check if aws-iam-authenticator is installed
+      #   run: |
+      #     which aws-iam-authenticator || echo "aws-iam-authenticator not found"
+      #     aws-iam-authenticator help
 
       # - name: Update kubeconfig for EKS
       #   env:
